repo: 'content-page'
canvasCourse: 'web-dev-2'

inherit:
  - naming-restrict-live
  - git-2
  - html
  - css-order-type-main
  - google-fonts
  - screenshots-all
  - typografier

html:
  - path: 'index.html'
    has:
      - 'article'
      - 'h1'
      - 'hr'
      - 'br'
      - 'header'
      - 'footer'
      - 'article > p'
      - 'blockquote'
      - 'blockquote > p'
      - 'blockquote > footer'
      - 'blockquote > footer > cite'
    search:
      - 'Queen of the Black Coast'
      - 'By Robert E. Howard, 1934'
      - '1. Conan Joins the Pirates'
      - 'The Song of Bélit'
      - 'Hoofs drummed down the street that sloped to the wharfs'
      - 'I am Conan, a Cimmerian'
      - '…'
      - 'text-'
      - 'gutter-'
      - 'push-'
      - 'pad-'
      - 'hang-punc'
      - 'max-length|wrapper'
      - 'italic'
      - 'not-italic'
      - 'bold|not-bold'

css:
  - path: 'css/main.css'
    locked: true
  - path: 'css/type.css'
    locked: true
